[tool.poetry]
name = "goalbert"
version = "0.1.0"
description = "GoalBERT: Goal-Directed ColBERT for Iterative Retrieval"
authors = ["Ben Giacalone <bensgiacalone@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
mypy = "1.8.0"
black = "24.2.0"
pytest = "8.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
